# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# 空行追加
add_newline = true

# タイムアウト時間
scan_timeout = 10

# 記号の設定
[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[directory]
truncation_length = 100
truncate_to_repo = false

[time]
#時間の表示をオンにして12時間表示に
disabled = false
use_12hr = true

[git_status]

[cmd_duration]
min_time = 500
format = "underwent [$duration](bold yellow)"
